"""adapt_new_excel

Revision ID: c3de593d0f92
Revises: 225ca9e7a76f
Create Date: 2025-04-20 19:20:46.020730

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c3de593d0f92'
down_revision = '225ca9e7a76f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diploma', schema=None) as batch_op:
        batch_op.drop_index('perfil')
        batch_op.drop_index('uvus')
        batch_op.drop_column('horas_en_total')
        batch_op.drop_column('comite')
        batch_op.drop_column('reuniones_asistidas')
        batch_op.drop_column('uvus')
        batch_op.drop_column('perfil')
        batch_op.drop_column('evidencias_registradas')
        batch_op.drop_column('horas_de_evidencia_aleatoria')
        batch_op.drop_column('evidencia_aleatoria')
        batch_op.drop_column('horas_de_evidencias')
        batch_op.drop_column('bono_de_horas')
        batch_op.drop_column('horas_de_asistencia')
        batch_op.drop_column('horas_de_reuniones')
        batch_op.drop_column('participacion')
        batch_op.drop_column('eventos_asistidos')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diploma', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eventos_asistidos', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('participacion', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('horas_de_reuniones', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('horas_de_asistencia', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('bono_de_horas', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('horas_de_evidencias', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('evidencia_aleatoria', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('horas_de_evidencia_aleatoria', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('evidencias_registradas', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('perfil', mysql.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('uvus', mysql.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('reuniones_asistidas', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('comite', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('horas_en_total', mysql.FLOAT(), nullable=True))
        batch_op.create_index('uvus', ['uvus'], unique=True)
        batch_op.create_index('perfil', ['perfil'], unique=True)

    # ### end Alembic commands ###
